server:
  port: 9998   #端口号
  servlet:
    context-path: /study    #项目访问路径

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiatou?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: qazwsx123
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: test
      lettuce:
        pool:
          min-idle: 0
          max-active: 8
          max-idle: 8
          max-wait: -1ms
      connect-timeout: 30000ms